### ISSUE TITLE
Would this work on Alteryx Gallery as well?

### ISSUE THREAD

**Issue by niravparikh** [bobpeers/Alteryx_SDK_Snowflake_Output#1] opened 2021-01-14 23:07 UTC
Hi Bob, thanks for writing the python snowflake connector, eager to try this out. Quick question , would this work on Alteryx Gallery? or it would run into the same javascript password encrypt , python password decrypt issue that we run into with other tools with html front end and python back end.  Would love to hear from you.

**Comment by bobpeers** [comment] 2021-01-15 06:56
Duplicate of #2

**Closed as completed by bobpeers** 2021-01-15 06:56 UTC
